language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

sudo: false

script: ./gradlew build